#!/usr/bin/env bash
# =============================================================================
# AXIONALYTICS — STATIC PAGE ASSEMBLER
# -----------------------------------------------------------------------------
# Concatenates shared chrome with per-page content into flat HTML files at the
# repository root, where GitHub Pages serves them.
#
#   <slug>.html  =  head-open + <slug>.meta + head-close + header
#                   + <slug>.body + footer
#
# The header and footer partials were extracted from the hand-built index.html
# so all pages stay byte-identical in their chrome. index.html itself is NOT
# generated — it is maintained directly, and is the source of truth for the
# partials. If you change the nav or footer, update index.html first, re-extract
# the partials, then re-run this script.
#
# Usage:  bash _build/scripts/build.sh
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
P="$ROOT/_build/src/partials"
G="$ROOT/_build/pages"

PAGES=(
  # Homepage. Was hand-maintained at root until make-i18n consumed it;
  # it is a build artifact now so the bilingual source always regenerates.
  index

  # Solution pillars
  solutions
  agentic-test-engineering
  enterprise-agentic-ai
  agentic-business-intelligence
  enterprise-ai-security
  agentic-revenue-development

  # Tools and company
  roi-calculator
  pricing
  case-studies
  about
  contact

  # Author page. Only exists once a name is set in _build/scripts/author.py;
  # build.sh skips it silently until then.
  author

  # Blog index + articles
  # Article meta/body pairs are generated by _build/scripts/make-articles.py from
  # content in _build/src/articles/. Run that first if content has changed.
  blog

  # Cluster articles supporting the security pillar
  why-ai-pilots-fail-security-review
  prompt-injection-tool-abuse-defense
  byoc-vs-saas-enterprise-ai

  # ... the agentic AI pillar
  human-in-the-loop-ai-architecture
  agentic-data-exploration-at-scale
  ai-tools-for-business

  # ... the test engineering pillar
  requirements-traceability-automation
  coverage-gap-analysis
  legacy-test-suite-modernization

  # ... the revenue development pillar
  outbound-research-not-volume
  email-deliverability-firewall

  # ... the business intelligence pillar
  bi-backlog-bottleneck
  excel-vs-power-bi
  data-analytics-roi
  business-dashboard-guide

  # Glossary — generated by _build/scripts/make-glossary.py
  glossary
  what-is-agentic-ai
  what-is-byoc
  what-is-human-in-the-loop
  what-is-prompt-injection
  what-is-email-deliverability
  what-is-a-semantic-layer
  what-is-requirements-traceability

  # Legal — generated by _build/scripts/extract-legal.py
  privacy
  terms
  accessibility
)

for slug in "${PAGES[@]}"; do
  meta="$G/$slug.meta.html"
  body="$G/$slug.body.html"

  if [[ ! -f "$meta" || ! -f "$body" ]]; then
    echo "  skip  $slug.html (missing meta or body)"
    continue
  fi

  cat "$P/head-open.html" \
      "$meta" \
      "$P/head-close.html" \
      "$P/header.html" \
      "$body" \
      "$P/footer.html" \
      > "$ROOT/$slug.html"

  printf '  build %-34s %6s bytes\n' "$slug.html" "$(wc -c < "$ROOT/$slug.html")"
done

echo "done."
