# -*- coding: utf-8 -*-
"""
Generate sitemap.xml across both language trees.

Each URL is emitted once per language with xhtml:link alternates naming every
version of that page, which is the form Google expects for hreflang declared in
a sitemap. Declaring it in both the page head and the sitemap is redundant on
purpose — the sitemap is what gets processed first on a new site.

Priorities reflect commercial intent rather than depth: the pillars and pricing
outrank the blog, which outranks legal.

Usage: python _build/scripts/make-sitemap.py
"""
import io
import os
import re
import importlib.util
from datetime import date

BASE = "https://www.axionalytics.com"
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TODAY = date.today().isoformat()

SKIP = {"datatransformation.html", "aitransformation.html",
        "training.html", "successstories.html"}

# slug -> (priority, changefreq)
WEIGHTS = {
    "index.html":                          ("1.0", "weekly"),
    "solutions.html":                      ("0.9", "monthly"),
    "agentic-test-engineering.html":       ("0.9", "monthly"),
    "enterprise-agentic-ai.html":          ("0.9", "monthly"),
    "agentic-business-intelligence.html":  ("0.9", "monthly"),
    "enterprise-ai-security.html":         ("0.9", "monthly"),
    "pricing.html":                        ("0.9", "monthly"),
    "roi-calculator.html":                 ("0.8", "monthly"),
    "contact.html":                        ("0.8", "monthly"),
    "case-studies.html":                   ("0.8", "monthly"),
    "glossary.html":                       ("0.8", "monthly"),
    "about.html":                          ("0.7", "monthly"),
    "blog.html":                           ("0.6", "weekly"),
    "privacy.html":                        ("0.2", "yearly"),
    "terms.html":                          ("0.2", "yearly"),
    "accessibility.html":                  ("0.2", "yearly"),
}
DEFAULT = ("0.7", "yearly")          # articles and glossary terms


def article_dates():
    spec = importlib.util.spec_from_file_location(
        "ma", os.path.join(ROOT, "_build", "scripts", "make-articles.py"))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return {a["slug"] + ".html": a["date"] for a in m.ARTICLES}


def url_for(slug, lang):
    tail = "" if slug == "index.html" else slug
    return "%s/%s%s" % (BASE, "es/" if lang == "es" else "", tail)


def main():
    dates = article_dates()
    pages = sorted(f for f in os.listdir(ROOT)
                   if f.endswith(".html") and f not in SKIP
                   and os.path.isfile(os.path.join(ROOT, f)))

    entries = []
    for slug in pages:
        prio, freq = WEIGHTS.get(slug, DEFAULT)
        lastmod = dates.get(slug, TODAY)

        for lang in ("en", "es"):
            alts = "\n".join(
                '    <xhtml:link rel="alternate" hreflang="%s" href="%s"/>' % (l, url_for(slug, l))
                for l in ("en", "es"))
            alts += ('\n    <xhtml:link rel="alternate" hreflang="x-default" href="%s"/>'
                     % url_for(slug, "en"))
            entries.append(
                "  <url>\n"
                "    <loc>%s</loc>\n"
                "%s\n"
                "    <lastmod>%s</lastmod>\n"
                "    <changefreq>%s</changefreq>\n"
                "    <priority>%s</priority>\n"
                "  </url>" % (url_for(slug, lang), alts, lastmod, freq, prio))

    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<!--\n'
           '  Generated by _build/scripts/make-sitemap.py — do not edit.\n'
           '  Both language trees are listed, each URL carrying xhtml:link\n'
           '  alternates for every language plus x-default.\n'
           '  Retired URLs (datatransformation, aitransformation, training,\n'
           '  successstories) are excluded: they are noindex redirect stubs.\n'
           '-->\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
           '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n\n'
           + "\n\n".join(entries) + "\n\n</urlset>\n")

    io.open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8").write(xml)
    print("  sitemap.xml  %d URLs (%d pages x 2 languages)  %.1f KB"
          % (len(entries), len(pages), len(xml.encode("utf-8")) / 1024.0))


if __name__ == "__main__":
    main()
