# -*- coding: utf-8 -*-
"""
Generate author.html, and register it for the build.

Runs only when a name has been supplied in author.py. Until then this is a
no-op: no page is written, no manifest entry is added, and nothing referencing
an unnamed author reaches the public.

Usage: python _build/scripts/make-author-page.py
"""
import io
import os
import re
import importlib.util

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def load_author():
    spec = importlib.util.spec_from_file_location(
        "author", os.path.join(ROOT, "_build", "scripts", "author.py"))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


META = u"""
  <title>{name} | {role_en} at Axionalytics</title>
  <meta name="description" content="{bio_short}">
  <link rel="canonical" href="{base}/author.html">
  <meta property="og:title" content="{name} | Axionalytics">
  <meta property="og:description" content="{bio_short}">
  <meta property="og:url" content="{base}/author.html">

  <script type="application/ld+json">
  {{
    "@context": "https://schema.org",
    "@type": "ProfilePage",
    "@id": "{base}/author.html#page",
    "mainEntity": {{
      "@type": "Person",
      "@id": "{base}/author.html#person",
      "name": "{name}",
      "jobTitle": "{role_en}",
      "description": "{bio_esc}",
      "url": "{base}/author.html",
      "worksFor": {{
        "@type": "Organization",
        "name": "Axionalytics",
        "url": "{base}/"
      }},
      "knowsAbout": [{knows}],
      "knowsLanguage": ["en", "es"]{same}
    }}
  }}
  </script>

  <script type="application/ld+json">
  {{
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {{ "@type": "ListItem", "position": 1, "name": "Home", "item": "{base}/" }},
      {{ "@type": "ListItem", "position": 2, "name": "{name}", "item": "{base}/author.html" }}
    ]
  }}
  </script>
"""

BODY = u"""
<!-- ==========================================================================
     AUTHOR PAGE — generated by _build/scripts/make-author-page.py
     ========================================================================== -->
<section class="ax-hero ax-noise relative pt-36 pb-16 lg:pt-44 lg:pb-20 overflow-hidden">
  <div class="ax-grid-bg"></div>
  <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 relative">

    <nav class="flex items-center gap-2 text-xs font-semibold text-white/35 mb-8 ax-reveal" aria-label="Breadcrumb">
      <a href="index.html" class="hover:text-ax-cyan transition-colors">
        <span data-lang-en>Home</span><span data-lang-es>Inicio</span>
      </a>
      <span>/</span>
      <span class="text-white/60">{name}</span>
    </nav>

    <h1 class="font-heading font-extrabold text-white text-[2.2rem] sm:text-4xl lg:text-[3rem] leading-[1.08] mb-4 ax-reveal">{name}</h1>
    <p class="text-lg text-ax-cyan font-semibold mb-6 ax-reveal">
      <span data-lang-en>{role_en}</span><span data-lang-es>{role_es}</span>
    </p>
    <p class="text-lg text-white/65 leading-relaxed ax-reveal">
      <span data-lang-en>{bio_en}</span><span data-lang-es>{bio_es}</span>
    </p>
  </div>
</section>

<section class="py-16 lg:py-20 bg-white">
  <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">

    <p class="ax-eyebrow text-ax-blue mb-6 ax-reveal">
      <span data-lang-en>Areas of work</span><span data-lang-es>&Aacute;reas de trabajo</span>
    </p>
    <div class="flex flex-wrap gap-2.5 mb-14 ax-reveal">
{topics}
    </div>

    <p class="ax-eyebrow text-ax-blue mb-6 ax-reveal">
      <span data-lang-en>Writing</span><span data-lang-es>Escritos</span>
    </p>
    <div class="space-y-3 ax-stagger">
{articles}
    </div>

    <div class="mt-14 pt-8 border-t border-ax-ink/10 flex flex-wrap items-center gap-4">
      <img src="assets/logo-mark.png" alt="" class="w-12 h-12 object-contain" width="141" height="160" loading="lazy" decoding="async">
      <div>
        <p class="font-heading font-bold">Axionalytics</p>
        <p class="text-sm text-ax-ink/55">
          <span data-lang-en>Quad Cities, Iowa &middot; working in English and Spanish</span>
          <span data-lang-es>Quad Cities, Iowa &middot; trabajamos en ingl&eacute;s y espa&ntilde;ol</span>
        </p>
      </div>
    </div>
  </div>
</section>

<section class="ax-band py-20 lg:py-24 relative overflow-hidden">
  <div class="ax-grid-bg opacity-50"></div>
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative ax-reveal">
    <h2 class="font-heading font-extrabold text-3xl lg:text-4xl text-white leading-[1.12] mb-5">
      <span data-lang-en>Bring the constraint that has been blocking you.</span>
      <span data-lang-es>Traiga la restricci&oacute;n que lo ha estado bloqueando.</span>
    </h2>
    <p class="text-lg text-white/60 leading-relaxed mb-9 max-w-2xl mx-auto">
      <span data-lang-en>Forty-five minutes, architecture-level, with the person who would do the work.</span>
      <span data-lang-es>Cuarenta y cinco minutos, a nivel de arquitectura, con quien har&iacute;a el trabajo.</span>
    </p>
    <a href="https://calendar.app.google/AYww7wSmkwANWDxR9" target="_blank" rel="noopener" class="ax-btn ax-btn-primary px-8 py-4">
      <span data-lang-en>Book a Technical Briefing</span><span data-lang-es>Agendar Sesi&oacute;n T&eacute;cnica</span>
    </a>
  </div>
</section>
"""

TOPIC = ('      <span class="ax-pill bg-ax-ink/5 text-ax-ink/70 '
         'border border-ax-ink/10">{t}</span>')

ROW = u"""      <a href="{slug}.html" class="ax-card p-5 block">
        <p class="text-2xs font-bold uppercase tracking-wider text-ax-blue mb-1.5">
          <span data-lang-en>{cat_en}</span><span data-lang-es>{cat_es}</span>
        </p>
        <p class="font-heading font-bold leading-snug">
          <span data-lang-en>{title_en}</span><span data-lang-es>{title_es}</span>
        </p>
      </a>"""


def main():
    a = load_author()
    out_meta = os.path.join(ROOT, "_build", "pages", "author.meta.html")
    out_body = os.path.join(ROOT, "_build", "pages", "author.body.html")

    if not a.enabled():
        for p in (out_meta, out_body):
            if os.path.exists(p):
                os.remove(p)
        print("  author name not set - author page not generated (site keeps "
              "Organization attribution)")
        return

    spec = importlib.util.spec_from_file_location(
        "ma", os.path.join(ROOT, "_build", "scripts", "make-articles.py"))
    ma = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(ma)

    same = [u for u in (a.LINKEDIN, a.GITHUB) if u]
    same_json = ""
    if same:
        same_json = ',\n      "sameAs": [%s]' % ", ".join('"%s"' % u for u in same)

    bio_short = re.sub(r"\s+", " ", a.BIO_EN)[:280]

    meta = META.format(
        base=a.BASE, name=a.esc(a.NAME), role_en=a.esc(a.ROLE_EN),
        bio_short=a.esc(bio_short), bio_esc=a.esc(re.sub(r"\s+", " ", a.BIO_EN)),
        knows=", ".join('"%s"' % a.esc(k) for k in a.KNOWS_ABOUT),
        same=same_json)

    topics = "\n".join(TOPIC.format(t=t) for t in a.KNOWS_ABOUT)
    articles = "\n".join(ROW.format(**art) for art in ma.ARTICLES)

    body = BODY.format(
        name=a.esc_html(a.NAME),
        role_en=a.esc_html(a.ROLE_EN), role_es=a.esc_html(a.ROLE_ES),
        bio_en=a.esc_html(a.BIO_EN), bio_es=a.esc_html(a.BIO_ES),
        topics=topics, articles=articles)

    io.open(out_meta, "w", encoding="utf-8").write(meta)
    io.open(out_body, "w", encoding="utf-8").write(body)
    print("  author.html generated for %s (%d articles listed)"
          % (a.NAME, len(ma.ARTICLES)))


if __name__ == "__main__":
    main()
