#!/usr/bin/env bash
# =============================================================================
# AXIONALYTICS — REDIRECT STUB GENERATOR
# -----------------------------------------------------------------------------
# GitHub Pages serves static files only; there is no server-side 301. The next
# best thing for both users and crawlers is a stub carrying:
#   - rel=canonical      → consolidates ranking signals onto the new URL
#   - meta refresh 0     → immediate client-side redirect
#   - noindex            → keeps the stub itself out of the index
#   - a visible link     → works when JS/meta-refresh is blocked
#
# Usage: bash _build/scripts/make-redirects.sh
# =============================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BASE="https://www.axionalytics.com"

emit() {
  local from="$1" to="$2" title_en="$3" title_es="$4"
  cat > "$ROOT/$from" <<HTML
<!DOCTYPE html>
<html lang="en">
<!--
  REDIRECT STUB — generated by _build/scripts/make-redirects.sh
  $from was retired in the 2026 re-architecture. Its content now lives at $to.
  The original page is preserved in _legacy/$from
-->
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="noindex, follow">
  <link rel="canonical" href="$BASE/$to">
  <meta http-equiv="refresh" content="0; url=$to">
  <title>Moved — $title_en | Axionalytics</title>
  <link rel="icon" type="image/png" href="assets/favicon-32.png">
  <script>window.location.replace("$to");</script>
  <style>
    body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;
         background:#0A101C;color:#fff;font-family:system-ui,-apple-system,sans-serif;text-align:center;padding:2rem}
    a{color:#22D3EE}
  </style>
</head>
<body>
  <main>
    <p style="opacity:.6;margin:0 0 .75rem">This page has moved.</p>
    <p style="margin:0"><a href="$to">$title_en &rarr;</a></p>
    <p style="margin:.5rem 0 0"><a href="$to" hreflang="es">$title_es &rarr;</a></p>
  </main>
</body>
</html>
HTML
  printf '  stub  %-30s -> %s\n' "$from" "$to"
}

emit "datatransformation.html" "agentic-business-intelligence.html" \
     "Agentic Business Intelligence" "Inteligencia de Negocios Agentica"
emit "aitransformation.html"   "enterprise-agentic-ai.html" \
     "Enterprise Agentic AI" "IA Agentica Empresarial"
emit "training.html"           "solutions.html" \
     "Solutions and enablement" "Soluciones y capacitacion"
emit "successstories.html"     "case-studies.html" \
     "Case Studies" "Casos de Exito"

echo "done."
